#!/usr/bin/env bash

  # add the flathub repo if it does nto exist (looking at you fedora)
  flatpak remote-add --if-not-exists flathubs https://flathub.org/repo/flathub.flatpakrepo

  # installs
  flatpak install -y "com.logseq.Logseq"
  flatpak install -y "com.github.tchx84.Flatseal"
  flatpak install -y "com.spotify.Client"
  flatpak install -y "com.system76.Popsicle"
  flatpak install -y "com.Transmissionbt.Transmission"
  flatpak install -y "org.gnucash.Gnucash"
  flatpak install -y "org.libreoffice.LibreOffice"
  flatpak install -y "org.mozilla.Thunderbird"
  flatpak install -y "org.videolan.VLC"
