#!/usr/bin/env bash

  mkdir -p $HOME/Source/github.com/

  git clone git@github.com:jeffwindsor/dotfiles.git $HOME/Source/github.com/jeffwindsor/dotfiles
  git clone git@github.com:jeffwindsor/financials.git $HOME/Source/github.com/jeffwindsor/financials
  git clone git@github.com:jeffwindsor/nixos-config.git $HOME/Source/github.com/jeffwindsor/nixos-config
  git clone git@github.com:jeffwindsor/startpage.git $HOME/Source/github.com/jeffwindsor/startpage
