#!/usr/bin/env bash

  mkdir -p $HOME/Source/github.com/

  git clone git@github.com:jeffwindsor/nixos-config.git $HOME/Source/github.com/jeffwindsor/nixos-config

  git clone git@github.com:jeffwindsor/financials-home.git $HOME/Source/github.com/jeffwindsor/financials-home
  git clone git@github.com:jeffwindsor/financials-wfp.git $HOME/Source/github.com/jeffwindsor/financials-wfp

  git clone git@github.com:jeffwindsor/startpage.git $HOME/Source/github.com/jeffwindsor/startpage
